local:
  yahoo:
    url: "https://tw.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"
  kktix:
    url: "https://kktix.com/"
    username: ${USERNAME}
    password: ${PASSWORD}

ut:
  yahoo:
    url: "https://us.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"

sit:
  yahoo:
    url: "https://hk.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"

uat:
  yahoo:
    url: "https://uk.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"