local:
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"
    username: "tomsmith"
    password: "HEROKU_APP_PASSWORD"  # SuperSecretPassword!
ut:
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"
    username: "tomsmith"
    password: "HEROKU_APP_PASSWORD"  # SuperSecretPassword!

sit:
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"
    username: "tomsmith"
    password: "HEROKU_APP_PASSWORD"  # SuperSecretPassword!

uat:
  heroku_app:
    url: "https://the-internet.herokuapp.com/login"
    username: "tomsmith"
    password: "HEROKU_APP_PASSWORD"  # SuperSecretPassword!