local:
  yahoo:
    url: "https://tw.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"

ut:
  yahoo:
    url: "https://us.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"

sit:
  yahoo:
    url: "https://hk.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"

uat:
  yahoo:
    url: "https://uk.yahoo.com"
  jph:
    url: "https://jsonplaceholder.typicode.com"