name: Python CI/CD with Schedule

on:
  schedule:
    - cron: '30 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 設定 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: 安裝專案依賴
      run: |
        pip install -r requirements.txt
    - name: 執行 Pytest 測試
      run: |
        python run.py --test_type api --env local -m "api"