name: Python CI/CD with Schedule

on:
  schedule:
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 設定 Python 環境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: 安裝專案依賴
        run: |
          pip install -r requirements.txt

      - name: 安裝 Allure  # 讓 allure 命令在環境中可用
        run: |
          sudo apt-get install -y openjdk-11-jre
          ALLURE_VERSION=2.34.0
          curl -LO https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
          tar -zxvf allure-$ALLURE_VERSION.tgz
          sudo mv allure-$ALLURE_VERSION /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/bin/allure
      - name: 檢查 Allure 命令是否可用
        run: |
          echo "PATH: $PATH"
          which allure
          allure --version # 嘗試執行 allure 命令，查看版本
        shell: bash

      - name: 執行 Pytest 測試
        run: |
          python run.py --test_type api --env local -m "api"